# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infra/rpc/creditlens.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'infra/rpc/creditlens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ainfra/rpc/creditlens.proto\x12\rcreditlens.v1\"K\n\x0cQueryRequest\x12\x13\n\x0b\x62orrower_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x14\n\x0c\x65\x66\x66\x65\x63tive_at\x18\x03 \x01(\t\"=\n\x0ePacketResponse\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\x13\n\x0bpacket_json\x18\x02 \x01(\x0c\x32S\n\x0cUnderwriting\x12\x43\n\x05Query\x12\x1b.creditlens.v1.QueryRequest\x1a\x1d.creditlens.v1.PacketResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infra.rpc.creditlens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=45
  _globals['_QUERYREQUEST']._serialized_end=120
  _globals['_PACKETRESPONSE']._serialized_start=122
  _globals['_PACKETRESPONSE']._serialized_end=183
  _globals['_UNDERWRITING']._serialized_start=185
  _globals['_UNDERWRITING']._serialized_end=268
# @@protoc_insertion_point(module_scope)
