include classpath("application.conf")
node-address {
  protocol = http
  host = "127.0.0.1"
  port = 19324
}
rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}
aws {
  region = us-east-1
  accountId = "000000000000"
}
