"""Compile a CPU serving lock constrained to the already evaluated project dependency versions."""

import argparse
import json
import shutil
import subprocess
from hashlib import sha256
from pathlib import Path
from tempfile import TemporaryDirectory


def run(command: list[str], repo: Path) -> str:
    """Use bounded literal argv; suppress registry errors that might contain secrets."""
    result = subprocess.run(  # noqa: S603 - fixed uv operations with explicit path arguments
        command, cwd=repo, capture_output=True, text=True, timeout=300, check=False
    )
    if result.returncode:
        raise RuntimeError(f"CPU dependency resolution failed with exit {result.returncode}")
    return result.stdout


def compile_lock(uv: str, repo: Path) -> None:
    """Keep the default environment untouched and select only the official PyTorch CPU backend."""
    if run([uv, "--version"], repo).split()[:2] != ["uv", "0.8.4"]:
        raise ValueError("Use the reviewed uv 0.8.4 resolver")
    with TemporaryDirectory(prefix="creditlens-cpu-lock-") as directory:
        temporary = Path(directory)
        constraints, requirements, output = (
            temporary / name for name in ("constraints.txt", "runtime.in", "runtime.lock")
        )
        # The exported constraints retain Python markers when one name has multiple versions.
        requirements.write_text("sentence-transformers\nnumpy\n", encoding="utf-8")
        run(
            [
                uv,
                "export",
                "--locked",
                "--no-dev",
                "--extra",
                "retrieval",
                "--no-emit-project",
                "--no-hashes",
                "--output-file",
                str(constraints),
            ],
            repo,
        )
        run(
            [
                uv,
                "pip",
                "compile",
                str(requirements),
                "--constraint",
                str(constraints),
                "--python-version",
                "3.11",
                "--python-platform",
                "x86_64-unknown-linux-gnu",
                "--torch-backend",
                "cpu",
                "--default-index",
                "https://pypi.org/simple",
                "--generate-hashes",
                "--no-build",
                "--no-annotate",
                "--no-header",
                "--output-file",
                str(output),
            ],
            repo,
        )
        content = (
            "# Generated by scripts/lock_neural_runtime.py with uv 0.8.4 for Linux CPU serving.\n"
            + output.read_text(encoding="utf-8")
        )
    destination = repo / "infra" / "retrieval"
    lock_path = destination / "requirements-cpu.lock"
    lock_path.write_text(content, encoding="utf-8", newline="\n")
    sources = {
        name: sha256((repo / name).read_bytes().replace(b"\r\n", b"\n")).hexdigest()
        for name in ("pyproject.toml", "uv.lock", "scripts/lock_neural_runtime.py")
    }
    manifest = {
        "schema": 1,
        "platform": "x86_64-unknown-linux-gnu",
        "python": "3.11",
        "resolver": "uv 0.8.4",
        "torch_backend": "cpu",
        "source_encoding": "UTF-8 with LF newlines",
        "source_hashes": sources,
        "lock_sha256": sha256(lock_path.read_bytes()).hexdigest(),
    }
    (destination / "cpu-lock-manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n"
    )


def main() -> None:
    """Resolve an installed uv binary without executing shell fragments or exposing credentials."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", default=shutil.which("uv"))
    args = parser.parse_args()
    if not args.uv:
        raise ValueError("An installed uv 0.8.4 executable is required")
    compile_lock(args.uv, Path(__file__).resolve().parents[1])


if __name__ == "__main__":
    main()
